[package]
name = "password"
version = "0.1.0"
authors = ["meaghanlewis <molewis@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
rand = "0.7"
assert_cmd = "1.0.1"